### ISSUE TITLE
If the object property name start with capital letter, Query return null value. 

### ISSUE THREAD

**Issue by mugzi86** [couchbaselabs/Linq2Couchbase#104]
In my couch Document object property name is defined as below (with capital letters). However if i try to search Types == airlines as in where clause it returns 0. It didn't return the document object. Please let me know any suggestion for this.

Couchbase Document - 
{
  "id": 24,
  "Type": "airline" // start with capital letter
}

Data Contract - 
[DocumentTypeFilter("airline")]
    public class Airline
    {
        [JsonIgnore]
        public string Id { get; set; }
        [JsonProperty("Type")]
        public string Type { get; set; }
    }

Linq Query - 
var query = context.Query<Airline>().Where(x => x.Type == "airline").ToList(); // return 0

**Comment by brantburnett** [comment]
@mugzi86 

Your issue is that the DocumentTypeFilter attribute assumes that the type property is lowercase.  So, you have a couple of options:

1.  Change JsonProperty to use "type" as a lowercase property name.

2.  Create a custom version of the DocumentTypeFilter, inherited from DocumentFilterAttribute, which uses the capitalized property name.  You can use DocumentTypeFilterAttribute as a guide:
https://github.com/couchbaselabs/Linq2Couchbase/blob/master/Src/Couchbase.Linq/Filters/DocumentTypeFilterAttribute.cs.
