### ISSUE TITLE
Debug Query

### ISSUE THREAD

**Issue by derix** [couchbaselabs/Linq2Couchbase#111]
Hi,

Is there a way to see what is the actual query sent to the couchbase DB? Meaning the translation of Linq to N1QL.

I ask that since I experiance slow perfomance and want to analyze the perfomance.

Best regards,

Oren

**Comment by brantburnett** [comment]
@derix 

Yes, this is supported via Common.Core logging, much like the main Couchbase SDK.

You'll need to use an adapter to link Common.Core logging to your own logger, such as log4net.  Then if you log Couchbase.Linq or Couchbase.Linq.BucketQueryExecutor at the Debug log level you should get the queries.

You can see the code doing the logging here:
https://github.com/couchbaselabs/Linq2Couchbase/blob/master/Src/Couchbase.Linq/BucketQueryExecutor.cs#L175

And you can see information about setting up Common.Core logging in the main SDK documentation:
http://docs.couchbase.com/developer/dotnet-2.1/setting-up-logging.html

Thanks,
Brant

**Comment by derix** [comment]
Many thanks for the prompt response.

For some reason when I run the query you print in the log (using cbq.exe), it returns 0 items in the results. But when I run it from the LINQ code I get many results.

cbq.exe> SELECT * FROM `suspectentity` as `Extent1` WHERE (((STR_TO_MILLIS(`Extent1`.`time`) >= STR_TO_MILLIS("2016-
   > 01-19T15:22:00Z")) AND (STR_TO_MILLIS(`Extent1`.`time`) <= STR_TO_MILLIS("2016-01-19T15:27:59.99Z"))) AND (`Extent1`.`channelId` = 2580));
{
    "requestID": "ef22f742-794a-42af-ba0d-21974d408a22",
    "signature": {
        "*": "*"
    },
    "results": [
    ],
    "status": "success",
    "metrics": {
        "elapsedTime": "545.0312ms",
        "executionTime": "545.0312ms",
        "resultCount": 0,
        "resultSize": 0
    }
}

**Comment by brantburnett** [comment]
@derix 

I'm not sure about how your development environment is configured, but is it possible you are hitting different Couchbase clusters?  By default, cbq also runs against localhost as the query server.  So if you have Couchbase installed locally on your dev box, but it isn't in the same cluster as you are using for your application, it could cause some confusion.

Brant

**Comment by derix** [comment]
I use a single environment with GSI indexes

I see that the query your code generated does not use the secondary indexes (using EXPLAIN):

EXPLAIN SELECT `Extent1`.`id` as `Id`, `Extent1`.`channelId` as `ChannelId`, `Extent1`.`time` as `Time`, CASE WHEN FALSE THEN `Extent1`.`signature` ELSE NULL END as `Signature`, `Extent1`.`isCdbSource` as `IsCdbSource`, CASE WHEN FALSE THEN `Extent1`.`picture` ELSE NULL END as `Picture`, `Extent1`.`metadata` as `Metadata` FROM `suspectentity` as `Extent1` WHERE (((STR_TO_MILLIS(`Extent1`.`time`) >= STR_TO_MILLIS("2016-
01-20T12:34:00Z")) AND (STR_TO_MILLIS(`Extent1`.`time`) <= STR_TO_MILLIS("2016-01-20T13:34:59.99Z"))) AND (`Extent1`.`channelId` = 2580)) LIMIT 10001;


While the same query manually written use the correct index:
EXPLAIN SELECT id, time from suspectentity where time >= '2016-01-19T10:00' and time <= '2016-01-19T10:10' and  channelId=12 LIMIT 10;

**Comment by cihanb** [comment]
Could you share the indexes you have and the full explain from the LINQ generated query and the command-line version?

**Comment by brantburnett** [comment]
@derix 

You piqued my interest on this one, so I decided to do a little experimentation myself.

First, let me discuss why the LINQ library outputs N1QL that uses STR_TO_MILLIS.  This was done to ensure consistent comparison handling of ISO date/time strings.  Performing a string comparison of an ISO date/time string (as in your example query) works under the basic use case of UTC.  However, as soon as you have your date/times in differing time zones, alphanumeric comparisons are no longer accurate.  "2016-01-01T5:00:00Z" is actually equal to "2016-01-01T4:00:00-01:00".

When writing your own queries, you can of course choose to ignore this.  For example, you may know that the date/time is always in UTC.  But for the LINQ library our goal is to make the behavior consistent with the .Net behavior, which pays attention to time zones when present.  We want to ensure that if you read the document out of Couchbase and did the comparison, you'd get the same result as you do in the N1QL query.  So we therefore use STR_TO_MILLIS to instruct N1QL to parse the string before comparing, and do the same thing with the constant value.

The downside to this approach is that it's not hitting your index.  So I did some experimenting in the beer-sample bucket to see what the behavior is.

If you make this index:
```
CREATE INDEX beerUpdated ON `beer-sample` (updated) USING GSI
```

Then run this EXPLAIN:
```
EXPLAIN SELECT * FROM `beer-sample` WHERE updated > '2010-07-22 20:00:20'
```

You will see that an IndexScan is performed.

On the other hand, this EXPLAIN doesn't use an IndexScan, it does a PrimaryScan:
```
EXPLAIN SELECT * FROM `beer-sample` WHERE STR_TO_MILLIS(updated) > STR_TO_MILLIS('2010-07-22 20:00:20')
```

Now for the really good news.  This can be easily fixed with a better index.  N1QL supports the concept of indexes that are calculated, invoking function calls against your data:
```
CREATE INDEX beerUpdatedMillis ON `beer-sample` (STR_TO_MILLIS(updated)) USING GSI
```

After making that index, you'll find that the second EXPLAIN statement is now performing an IndexScan.

Hope this helps.

Brant

**Comment by derix** [comment]
Many thanks for your prompt support and detailed explanation.
