### ISSUE TITLE
Select subquery is not supported in Couchbase.Linq.QueryGeneration.N1QlQueryModelVisitor.VisitSubQueryFromClause hence limits oData usage

### ISSUE THREAD

**Issue by wiciul** [couchbaselabs/Linq2Couchbase#134]
OData endpoint with method like:
`        [EnableQuery(PageSize = 500)]
        public IHttpActionResult Get()
        {
            return Ok(_unresolvedCoverageLogContext
                .Query<UnresolvedCoverageLogEntry>()
                .ProjectTo<AddUnresolvedCoverageRequest>());
        }`

cannot be used with $select option (e.g. http://localhost:53053/preanalyst/api/AddUnresolvedCoverageRequests/?$select=AnalystCode&$top=10) 

Obviously error is thrown:
Type : System.NotSupportedException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
	Message : Subqueries In The Main From Clause Are Only Supported For Grouping And Unions
	Source : Couchbase.Linq
	Help link : 
	Data : System.Collections.ListDictionaryInternal
	TargetSite : Void VisitSubQueryFromClause(Remotion.Linq.Clauses.MainFromClause, Remotion.Linq.Clauses.Expressions.SubQueryExpression)
	HResult : -2146233067
	Stack Trace :    at Couchbase.Linq.QueryGeneration.N1QlQueryModelVisitor.VisitSubQueryFromClause(MainFromClause fromClause, SubQueryExpression subQuery)
	   at Couchbase.Linq.QueryGeneration.N1QlQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
	   at Remotion.Linq.Clauses.MainFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
	   at Couchbase.Linq.QueryGeneration.N1QlQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
	   at Couchbase.Linq.Execution.BucketQueryExecutor.ExecuteCollection(QueryModel queryModel, Boolean selectDocumentMetadata, ScalarResultBehavior& scalarResultBehavior)
	   at Couchbase.Linq.Execution.BucketQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
	   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
	   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
	   at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
	   at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
	   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
	   at Remotion.Linq.QueryableBase`1.GetEnumerator()
	   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	   at System.Web.OData.Query.TruncatedCollection`1..ctor(IQueryable`1 source, Int32 pageSize)
	   at System.Web.OData.Query.ODataQueryOptions.LimitResults[T](IQueryable`1 queryable, Int32 limit, Boolean& resultsLimited)

Can you extend functionality to support such case?
I am running into it with nuget package version 1.1.0.2

**Comment by brantburnett** [comment]
@wiciul 

I'd have to do some digging to see how doable this would be.  The problem is that N1QL doesn't support the idea of a subquery in the from clause like SQL does (i.e. SELECT * FROM (SELECT * FROM bucket WHERE x = y).

Depending on the LINQ expression tree being generated, it may be possible to simplify it.  I'm not really sure why the OData stuff would be generating a LINQ query of this type, though.  Maybe an additional select projection to rename the columns?

Is there any way that you can show me what the generated LINQ query looks like, before it gets passed to the library to be converted to N1QL?  Or at least what the OData parameters that are being sent through are?

A sample application that I could step through in debug mode would probably be the most helpful, if that's an option.

Brant

**Comment by wiciul** [comment]
Please find the example:
https://github.com/wiciul/couchbase-net-sample-linq2couchbase-odata 
You can use fiddler captures found here: https://github.com/wiciul/couchbase-net-sample-linq2couchbase-odata/blob/master/Couchbase.BeerSample.Web/Fiddler/odatarequests.saz

I think there is something to review as this is rather projection than subquery.

Additionally I think it has already worked (I think I have checked odata $select) with what you have delivered here: https://github.com/brantburnett/Linq2Couchbase/tree/issue85-strongtypeprojections

**Comment by brantburnett** [comment]
@wiciul 

Have you updated to 1.1 yet?  That version includes the work on issue #85.

Brant

**Comment by wiciul** [comment]
@brantburnett let me repeat, I am running into it with nuget package version 1.1.0.2
Projection to strong types works. Projection with oData runs into that issue reported. Please try example application.

**Comment by brantburnett** [comment]
@wiciul 

Okay, just wanted to double check.  I just saw my reminder to look at this because i hadn't yet.  Hopefully I'll know something in the next few days.

**Comment by brantburnett** [comment]
@wiciul 

I've got good news and bad news about supporting this.  First, the good news.

I've uploaded a WIP commit that adds support for the query being generated by your sample.  The specific issue is that an inner query is created with a select projection to your BeerOdataModel, filters and limits are applied, etc.  Applying the $select clause then causes it to apply a secondary select projection to another type.  This WIP commit recognizes this, and generates the correct query to produce the JSON object requested.

The bad news is that this fix is not sufficient to do everything you require.  The problem is that, while the data is being returned as requested, it can't be deserialized from JSON into the requested object type.  OData is requesting a SelectSome<T> class, which inherits from SelectExpendWrapper<T>.  This class has a JsonConverter assigned by attribute which doesn't support deserialization at all.

https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Query/Expressions/SelectExpandWrapper.cs
https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Query/Expressions/SelectExpandWrapperConverter.cs

There might be some way for you to work around this on your side by registered your own custom JsonConverter that change the behavior.  But this would be difficult since the classes in question are marked internal.

Frankly, I'm a bit stumped at the moment with how Entity Framework even supports this kind of query.  But I'll keep looking for an option on the Linq2Couchbase side that supports this, too.  I have some more ideas.  Please let me know if you find any trick to fix the deserialization on your side.

Brant

**Comment by wiciul** [comment]
@brantburnett 

Quick research shows that it might not be possible to register custom JsonConverter.
Take a look at this:
`        [EnableQuery(MaxTop = 100)]
        public IQueryable<BeerOdataModel> Get(ODataQueryOptions opts)
        {
            var odataQuery = opts.ApplyTo(BeerContext.Query<Beer>().ProjectTo<BeerOdataModel>());
            var odataResult = (odataQuery as IQueryable<dynamic>).ToList();
            var filteredQuery = BeerContext.Query<Beer>().ProjectTo<BeerOdataModel>().Select(b => b.Name);
            var filteredList = filteredQuery.ToList();
            return BeerContext.Query<Beer>().ProjectTo<BeerOdataModel>();
        }`

Are you sure there is no possibility to simplify query tree caused by this line: `opts.ApplyTo(BeerContext.Query<Beer>().ProjectTo<BeerOdataModel>())` with SelectExapndQueryOption not null so its execution would result in n1ql as execution of this line: `BeerContext.Query<Beer>().ProjectTo<BeerOdataModel>().Select(b => b.Name)` ? There is no option that they both could produce the same query: `SELECT `Extent1`.`name` as `result` FROM `beer-sample` as `Extent1` WHERE (`Extent1`.`type` = 'beer')` ?

**Comment by brantburnett** [comment]
@wiciul 

So, the WIP commit I linked in my earlier comment will address your request.  It will take this query:

```csharp
BeerContext.Query<Beer>().ProjectTo<BeerOdataModel>().Take(10).Select(b => b.Name)
```

And convert it to this query (or something similar):

```csharp
SELECT `Extent1`.`name` as `name` FROM `beer-sample` as `Extent1` LIMIT 10
```

The issue is that's not what OData is doing.  It's trying to make something more like this query:

```csharp
BeerContext.Query<Beer>().ProjectTo<BeerOdataModel>().Take(10).Select(b => new SelectSome<BeerOdataModel> {
  .ModelID = guidConstant,
  .Container = new PropertyContainer() {
    .Name = "Name",
    .Value = b.Name
  }
})
```

This is what's causing the difficulties, as the SelectSome<T> class can't be deserialized from JSON using Newtonsoft.Json, at least not without some custom converters.

As I mentioned, I do have a couple of other ideas.  But they're much more complicated and problematic.  It involves delaying part of the select projection until after the data is requested and deserialized when it contains constants like the guidConstant and Name fields above.  Due to the complexity, it will probably be a while before something gets done, if it's even possible.

Brant

**Comment by wiciul** [comment]
Thanks. I see it (difficulty) clear it right now. Anyway I keep fingers crossed for eventual solution. Thanks.

**Comment by wiciul** [comment]
@brantburnett 

Is there a way to deserialize to intermediate anonymous object?
```
BeerContext.Query<Beer>().ProjectTo<BeerOdataModel>().Take(10)
    
.Select(b => new {
    ModelID = guidConstant,
    Name = "Name",
    NameValue = b.Name, // which is odata entity (BeerOdataModel) key in this case as well hecen perhpash Id column/field doesn't need to be included
})
    
.ToList() // materilize/deserialize here
    
.Select(b => new SelectSome<BeerOdataModel> {
  .ModelID = guidConstant,
  .Container = new PropertyContainer() {
    .Name = "Name",
    .Value = b.Name
  }
})
```
What do you think about that?

Thanks.

**Comment by brantburnett** [comment]
@wiciul 

Yeah, that's basically what I was thinking about doing behind the scenes.  But making it happen automatically, and against internal classes, is more than a little tricky.  But I'm going to keep thinking about it.

**Comment by wiciul** [comment]
@brantburnett 

On the other hand I will try to present it to WebApi.OData team. Perhaps they could extend something and not be limited only EF or materialized collections with IQueryable interface.

**Comment by dgcaron** [comment]
i ran into the same issue, and i found a way around this. You can use DynamicLinq (https://github.com/StefH/System.Linq.Dynamic.Core) to parse the $select to an anonymous object (or expression). What i ended up doing is, inherit from the EnableQuery attribute and override the OnActionExecuted,  The select statement is very straight forward:

```
 public static IQueryable Select(this IQueryable queryable, SelectExpandQueryOption options)
        {
            if (options == null)
            {
                return queryable;
            }

            return queryable.Select(string.Format("new ({0})", options.RawSelect));
        }
```
