### ISSUE TITLE
Queries fail if DefaultSerializer.ContractResolver is null

### ISSUE THREAD

**Issue by rogeralsing** [couchbaselabs/Linq2Couchbase#150]
Assuming this code:

```csharp
var config = new ClientConfiguration();
var jsonSettings = new JsonSerializerSettings
{
       Binder = SerializationBinder,
       TypeNameHandling = TypeNameHandling.All,
};
config.Serializer = () => new DefaultSerializer(jsonSettings, jsonSettings);
var cluster = new Cluster(config);
var bucket = cluster.OpenBucket("MyBucket");
var context = new BucketContext(bucket);
```

Queries will fail at this line:

```csharp
        //ExtendedTypeSerializerMemberNameResolver.cs
  
        public bool TryResolveMemberName(MemberInfo member, out string memberName)
        {
            memberName = null;

            if (member == null)
                return false;

            memberName = _serializer.GetMemberName(member);  //BOOM, here

            return memberName != null;
        }
```

By setting a `ContractResolver = new CamelCasePropertyNamesContractResolver()` on the json settings, this problem is resolved.

The BucketContext should probably throw if the client configuration does not provide the above.

**Comment by brantburnett** [comment]
@rogeralsing 

It might also be possible to fallback to the Json.net default contract resolver if it isn't specified, I'm not sure I'll have to look into it further.

However, this is actually an issue in the main Couchbase SDK, rather than the LINQ provider.  That is where GetMemberName is implemented and could be improved.

I've filed an issue on the main SDK here: https://issues.couchbase.com/browse/NCBC-1155

Thanks,
Brant

**Comment by jeffrymorris** [comment]
Created an SDK ticket here: https://issues.couchbase.com/browse/NCBC-1157
