### ISSUE TITLE
Resource file error

### ISSUE THREAD

**Issue by timtim002hk** [couchbaselabs/Linq2Couchbase#198]
After added Linq2Couchbase 1.3.2, an error occurred when modify the resource file.
I am using Visual Studio 2017.

**Comment by jeffrymorris** [comment]
@timtim002hk -

What error and what modification to the resource file?

-Jeff

**Comment by timtim002hk** [comment]
![default](https://cloud.githubusercontent.com/assets/2551501/26756479/dca40342-48d5-11e7-816e-44c153d76685.PNG)

**Comment by brantburnett** [comment]
@timtim002hk 

That's very unusual.  It only happens when you have Linq2Couchbase installed, and it's consistent?

I'm not sure what in Linq2Couchbase could trigger this.  I would suspect it's a bug in Visual Studio or a VS Extension.  Have you installed all of the latest Visual Studio updates?  Also, have you tried disabling Resharper if you have that installed?

Brant

**Comment by timtim002hk** [comment]
I have installed all of the latest Visual Studio updates and did not install Resharper. But i try to create two project that are "Asp.net Core 1.0" and "Asp.net Core 1.1" respectively. i found this error only occurred on "Asp.net Core 1.1".
