### ISSUE TITLE
Remotion.Linq Dependencies

### ISSUE THREAD

**Issue by miridfd** [couchbaselabs/Linq2Couchbase#202]
Hello,

Remotion.Linq nuget package, version 2.1.1, pulls a bunch of .NET System nugets, even though that the target framework is not ".NET Standard" but .NET Framework 4.6.

Can you please clarify whether this behavior is expected? it actually blows up the dependencies of the project for nothing.

Thanks,
Miri

**Comment by brantburnett** [comment]
@miridfd 

This is, unfortunately, something outside of our control.  This behavior is because the Remotion.Linq package targets .NET Standard 1.0 only, rather than dual targeting .NET 4.5 and .NET Standard 1.0.

The good news is that .NET Standard was designed to account for this.  Most of the dependencies actually don't do anything, or if they do it just installs a very small assembly that adds a couple of small methods missing from the desktop version of .NET.  But you are correct, it does add additional dependencies to packages.config that appear unnecessary.

If you have further questions, I'd recommend filing an issue with Remotion.  Their issue tracker is at https://www.re-motion.org/jira/projects/RMLNQ/issues.  They might be able to give better feedback about why they chose this packaging approach.

Brant

**Comment by miridfd** [comment]
Thank you for the detailed and informative answer. I'll log an issue on Remotion project.

**Comment by miridfd** [comment]
Link to the opened issue on the Remotion project:
https://www.re-motion.org/jira/projects/RMLNQ/issues/RMLNQ-113

Miri
