### ISSUE TITLE
Building OData endpoints with Linq2Couchbase

### ISSUE THREAD

**Issue by drGarbinsky** [couchbaselabs/Linq2Couchbase#222]
I have been working on building an OData endpoint in ASP .Net using Liqn2Couchbase. I have recently bumped into a situation where I am unable to support the $select and $expand operators in  OData. There are several symptoms that are blocking progress but they all revolve around query generation issues. My main question is if Linq2Couchbase is intended to be used in an ad-hoc situation or if that should be avoided.

**Comment by brantburnett** [comment]
@drGarbinsky 

The Linq2Couchbase library is certainly designed to work in an ad-hoc scenario.  Historically, the issue has been that OData generates lambdas that are exceedingly complex and difficult to convert to N1QL queries.  I think we can probably bring it into alignment so that it will work.  But it will probably require identifying particular OData scenarios that don't work and filing individual issues for them.  We could use this issue as a master issue to track the others.

Additionally, I would point out that you must be careful with ad-hoc queries against Couchbase.  Due to the scale of data involved in Couchbase, which is often much larger than in traditional RDBMS, index optimization for queries becomes very important.  If you're providing ad-hoc query support for documents of a specific type which only has a few hundred documents you're probably okay.  But at larger scales you can encounter performance issues.  The new adaptive indexes in Couchbase Server 5.0 might help as well, but they tend to generate **very** large indexes.

**Comment by drGarbinsky** [comment]
@brantburnett  that's good to hear. I'll keep my current plan to invest in that approach. My planned next step is to capture the offending scenarios in sample code that other can use for a repro. It might be a bit before I get to that so feel free to close this issue.
