### ISSUE TITLE
Enum comparison does not work when serialized as a string

### ISSUE THREAD

**Issue by gbrown-ce** [couchbaselabs/Linq2Couchbase#246]
If your couchbase documents have enum properties that are serialized as a string (using StringEnumConverter), when you do a comparison in a linq where clause, it always uses the numeric value instead of the string value causing the comparison to always fail.  A temporary workaround being using ToString on each ends of the comparison. 

```where document.EnumType == EnumType.FirstValue```

becomes

```where document.EnumType.ToString() == EnumType.FirstValue.ToString()```

That isn't even entirely accurate as you may have other decorators that cause the enum to serialize differently (EnumMember).

**Comment by jeffrymorris** [comment]
@gbrown-ce -

Thanks for submitting, we'll look deeper into this.

-Jeff

**Comment by brantburnett** [comment]
@gbrown-ce @jeffrymorris 

I spent a bunch of time looking at this over the weekend.  I've come the conclusion that what is required is a substantiative rewrite of how we're handling custom JsonConverters.  The current approach is very specific to the UnixMillisecondsConverter for date/times, but we need something more generic and extensible that can apply to other converters such as the StringEnumConverter.  Once this framework is in place, it should make supporting additional converters much easier.

At this point I have some work in progress that's getting close, I'm just encountering lots of edge cases that it creates around comparison operators which need to be addressed.  Hopefully I'll have something in the next 1-2 weeks.

I do think that we need to help final release of 1.4 until this issue is resolved.  There were API changes made in 1.4-beta to support UnixMillisecondsConverter that will be undone to support this new approach.  If we release 1.4 final it will then result in SemVer breaking changes, but if we wait we'll be fine.  I'd also propose, due to the significance of the changes, that once they're complete we roll 1.4-beta2 for a bit to be safe.

**Comment by jeffrymorris** [comment]
@brantburnett  -

Thanks for looking into this and agree we should hold off on 1.4 and instead do a 1.4.0-beta2.

-Jeff

**Comment by jeffrymorris** [comment]
@brantburnett  Can we close this?

**Comment by brantburnett** [comment]
@jeffrymorris yes!

**Comment by jeffrymorris** [comment]
@gbrown-ce thanks for reporting
@brantburnett thanks for fixing 👍
