### ISSUE TITLE
Couchbase.N1QL namespace and Couchbase.Linq.N1QL class conflict

### ISSUE THREAD

**Issue by jeffrymorris** [couchbaselabs/Linq2Couchbase#62]
https://issues.couchbase.com/browse/LINQ-22

**Comment by brantburnett** [comment]
So, the standard in EF is to put SQL specific functions in a shared type called EntityFunctions:

https://msdn.microsoft.com/en-us/library/system.data.objects.entityfunctions(v=vs.110).aspx

What about something similar for N1Ql, like N1QlFunctions.  Then we could start putting other N1QL specific functions there for query emulation.

Alternatively, we could go with a route for N1QL functions that is grouped by type of function.  So, N1QlMetadata (Would contain Meta and Key functions).  Then if we add other N1Ql functions (say special date functions) they could go in N1QlDate.XXX.  Downside here is a bit of repetitiveness, since we'd have a call to N1QlMetadata.Meta.

Brant

**Comment by jeffrymorris** [comment]
@brantburnett 

 N1QlFunctions would work, but it's a bit verbose. I am not sure what else we could use here...:(

-Jeff
