### ISSUE TITLE
META() does not serialize correctly

### ISSUE THREAD

**Issue by jeffrymorris** [couchbaselabs/Linq2Couchbase#68]
~~https://issues.couchbase.com/browse/LINQ-23~~

https://issues.couchbase.com/browse/NCBC-1021

**Comment by brantburnett** [comment]
@jeffrymorris 

The problem is probably the way we're wrapping it.  If you put it inside a new like this I believe it works:

`new with {.meta = N1Ql.Meta(p)}`

We probably need to add handling for this use case.

Brant

**Comment by jeffrymorris** [comment]
@brantburnett  -

It appears to be something on the SDK side; the generated N1QL statement is valid and works in CBQ:

cbq> SELECT META(`Extent1`) FROM `beer-sample` as `Extent1` LIMIT 1;
{
    "requestID": "d3fe60fc-6742-49e3-8cf6-110669a040ef",
    "signature": {
        "$1": "object"
    },
    "results": [
        {
            "$1": {
                "cas": 1.4454516563845448e+18,
                "flags": 0,
                "id": "21st_amendment_brewery_cafe-563_stout",
                "type": "json"
            }
        }
    ],
    "status": "success",
    "metrics": {
        "elapsedTime": "52.771019ms",
        "executionTime": "52.730494ms",
        "resultCount": 1,
        "resultSize": 214
    }
}

I'll dig through the SDK and see why it's not mapping correctly (the "$1" looks suspect, though).

-Jeff

**Comment by brantburnett** [comment]
So, after some further research I think this really is an issue we need to handle on the Linq2Couchbase library side.  It isn't just affecting the META keyword, but basically other use cases that don't include a select project.

This use case is working:

from beer in context.Query<Beer>()
select beer;

It works because we automatically add ".*" in the query:

SELECT `Extent1`.* FROM `beer-sample` as `Extent1`

This projects all the properties of the beer out into the result object for us, so we don't have to do it manually.

Additionally, with a small tweak we can apply the same approach to the META function by adding ".*".

SELECT META(`Extent1`).* FROM `beer-sample` as `Extent2`

This will fix the META keyword if we are attempting to return it directly, with "new {...}" in the select projection.  However, there are other use cases that this doesn't fix.

For example, trying to select a single property directly from the object:

from b in context.Query<Beer>()
select b.Abv;

Produces a similar problem.  The decimal result is wrapped inside a $1 object in the result array.  But the deserialization routine is expecting an array of plain numbers, not objects with a property.  There was a similar problem when dealing with subqueries which was addressed using the ARRAY keyword: https://github.com/couchbaselabs/Linq2Couchbase/commit/4207bd70cc7cff214f3ca772aba8d4d1c441130d#diff-11633180655c66f27a9a13a17422ff83R181

I think that the better fix is going to be a resolution that addresses both cases where there is no "new" in the select projection, not just the META case.

Brant

**Comment by brantburnett** [comment]
Jeff,

I think that this issue can be closed now, unless there some particular aspect of it I missed.

Thanks,
Brant
