### ISSUE TITLE
Request to make DocumentFilterManager public in order to register custom filter

### ISSUE THREAD

**Issue by wiciul** [couchbaselabs/Linq2Couchbase#83]
Can you make DocumentFilterManager public? I would like to register custom filters in constructor of class extending bucket context.

**Comment by brantburnett** [comment]
@wiciul 

You raise a good point.  I think we might have gotten a little overzealous when we were reducing the public API footprint.  When I wrote it I had originally intended for registering via DocumentFilterManager to be an accessible endpoint.  It allows for registering filters with code instead of attributes, which is especially important if you're using POCOs from a library.

I'll take a look at it an see how involved it's going to be.  Before I make it public we'll want to review it again and make sure we still like the API approach and that we're not making it too complicated or cumbersome.

Thanks!

**Comment by wiciul** [comment]
@brantburnett  
For right now I have bucket of homogeneous documents so I don't need predicate but in the future I would like not pollute library with my POCOs referring data access code. Btw. whole idea of Linq to N1QL is just great! Thanks to that we can maintain our approach with OData...I am waiting impatiently for nuget package which will not be prerelease:)

**Comment by brantburnett** [comment]
@wiciul 

We have a release 1.0.2 available:

https://www.nuget.org/packages/Linq2Couchbase/

**Comment by jeffrymorris** [comment]
See: https://github.com/couchbaselabs/Linq2Couchbase/commit/35ee9016e8587c11bb507c388006d43fbd0e60e8
