### ISSUE TITLE
Enums Not Supported

### ISSUE THREAD

**Issue by jawang35** [couchbaselabs/Linq2Couchbase#88]
I couldn't find information in the documentation about this anywhere. Are there any plans to offer the ability to filter enum properties and enum flags?

**Comment by brantburnett** [comment]
@jawang35 

You raise a very good question.  It's certainly an excellent feature I'd like to see added.  The trick is going to be matching the way enumerations are represented in N1QL with the way they're being serialized in the documents.

Can you provide some examples of the serialization method you're using in your use case?  For example, are you using StringEnumConverter in Json.net?

**Comment by jeffrymorris** [comment]
@jawang35, @brantburnett -

Here is a blog regarding enum support in EF: http://blogs.msdn.com/b/efdesign/archive/2011/06/29/enumeration-support-in-entity-framework.aspx

Checkout the "Query" and "HasFlags" support sections specifically, is this what you envision the support would cover? HasFlags would have to be translated into multiple "OR"s in the predicate.

-Jeff

**Comment by jawang35** [comment]
@brantburnett , @jeffrymorris 

I am using StringEnumConverter and I did imagine it would be implemented just like enums are supported in EF. The only difference being possibly allowing the enums to be stored as strings instead of their underlying value type when StringEnumConverter is used. If that is the case then translating the predicate will have to take into consideration whether the converter is specified. I think by default (when StringEnumConverter is not used) the underlying value type will have to be stored because of the ability for two enum members to have the same underlying value.

**Comment by brantburnett** [comment]
@jawang35 

I've put in pull request #96, which should add the support you are looking for to the next release.  It will allow your use of StringEnumConverter to pass through to the N1QL query, so long as you are using == or != comparisons.

Regarding enum flags, that's a bit more complicated.  The work that was done should support == and != checking of flags, so long as the JSON converter supports them, and it always writes the flags consistently.  Note that I don't think StringEnumConverter supports flags.

However, it still won't support doing bitwise operations on the flags.  At this time, I can't find any documentation where N1QL supports bitwise operations in the query.  My recommendation at this time, unfortunately, is to do any bitwise filtering in code rather than in query:

```
var docs = context.Query<Document>()
    .Where(p => p.Age > 10)
    .AsEnumerable()
    .Where(p => (p.Flags & Flag.One) == Flag.One);
```

Note that any lambdas applied after an AsEnumerable() call are executed in code, after the query is complete.  This is less performant than filtering done in the query, but required to do things unsupported by the LINQ query engine.

Thanks,
Brant
